/** Topic-code edges: finish `from` before `to`. */
export const TOPIC_PREREQS: [string, string][] = [
  ["PDS-C", "PDS-REC"],
  ["PDS-C", "PDS-LINEAR"],
  ["PDS-C", "PDS-LL"],
  ["PDS-C", "PDS-TREES"],
  ["PDS-C", "PDS-GRAPHS"],
  ["PDS-C", "ALGO-SORT"],
  ["PDS-C", "ALGO-ASYM"],
  ["PDS-LINEAR", "ALGO-DESIGN"],
  ["PDS-GRAPHS", "ALGO-GRAPH"],
  ["DM-LOGIC", "TOC-FA"],
  ["DM-GRAPHS", "TOC-FA"],
  ["TOC-FA", "TOC-CFG"],
  ["TOC-CFG", "TOC-CFL"],
  ["TOC-CFL", "TOC-TM"],
  ["TOC-FA", "CD-PARSE"],
  ["TOC-CFG", "CD-PARSE"],
  ["DL-BOOL", "COA-ISA"],
  ["DL-CIRCUITS", "COA-ALU"],
  ["DL-ARITH", "COA-CACHE"],
  ["PDS-C", "OS-PROC"],
  ["PDS-C", "OS-SYNC"],
];
